### ISSUE TITLE
Question about .vuepress/styles/index.styl

### ISSUE THREAD

**Issue by rajaraodv** [pskordilakis/vuepress-plugin-tabs#1]
Hi thanks for the plugin!
Wondering if we need to eject Vuepress to get the `styles` folder or just create a new folder called `styles` and create a file called `index.styl` and then `@require '~vuepress-plugin-tabs/dist/themes/default.styl'` in that file?

**Comment by pskordilakis** [comment]
Hi, 
sorry I do not understand what you mean with eject Vuepress to get the styles folder.

You can create the file .vuepress/styles/index.styl and require the default theme.
[index.styl](https://vuepress.vuejs.org/config/#index-styl) is the official way to add extra styles to a Vuepress installation.

**Comment by rajaraodv** [comment]
ah! didnt know about index.styl

thanks!

closing this
